services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expressativo_development
      MYSQL_USER: expressativo
      MYSQL_PASSWORD: expressativo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=expressativo
      - MYSQL_PASSWORD=expressativo
      - MYSQL_DATABASE=expressativo_development
      - RAILS_MASTER_KEY=e0dd59794f472bd4f873d97d733ccc62
    volumes:
      - .:/rails
    depends_on:
      - db

volumes:
  mysql_data: