services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tebook_local_db
      MYSQL_USER: expressativo
      MYSQL_PASSWORD: expressativo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        RAILS_ENV: development
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tebook_local_db
      - DB_USERNAME=expressativo
      - DB_PASSWORD=expressativo
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
    depends_on:
      - db

volumes:
  mysql_data: